### ISSUE TITLE
Error on instructions to build for raspberry pi

### ISSUE THREAD

**Issue by diogoviannaaraujo** [joshmarinacci/aminolang#10]
In the raspberry build instructions you say to install libpng and libjpeg, but in raspbian this package is not available. Can you fix the instructions?

**Comment by joshmarinacci** [comment]
Sorry. This project has been moved to a new repo called aminogfx.

https://github.com/joshmarinacci/aminogfx

The instructions here explain how to install png and jpeg libs on Raspian.
- J
