### ISSUE TITLE
Version of Node

### ISSUE THREAD

**Issue by fu-raz** [joshmarinacci/aminolang#12]
I'm trying to build this on a Linux device, but I'm not sure why it's not building. It gives my soo many errors, that I'm thinking it has to do with my version of Node. I'm using Node v7.10.0 and Node-Gyp v3.6.2 at the moment.

What version of Node is this known to be working on?

**Comment by joshmarinacci** [comment]
This was built during the pre Node v4 era, so it probably won't work anymore. All work on this project has moved to the OpenGL version here: Try that one instead.  https://github.com/joshmarinacci/aminogfx-gl
